<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <title>Timeline</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
   <nav class="navbar navbar-expand-md" style="background-color:#ffffff;line-height:33px">
         <div  class="nav_head collapse navbar-collapse ml-1" id="collapse-1">
               <ul class="nav navbar-nav">
                  <li >
                        <a style="text-decoration:none;color:grey;font-size:15px;font-weight:700"class="mr-4" href="#">Timeline</a>
                        <a style="text-decoration:none;color:grey;font-size:15px;font-weight:700"class="mr-4" href="#">Releases</a>
                        <a style="text-decoration:none;color:grey;font-size:15px;font-weight:700"class="mr-4"href="#">Collabolators</a>
                        <a style="text-decoration:none;color:grey;font-size:15px;font-weight:700"href="#">Settings</a>
                  </li>
               </ul>
            </div>
   </nav>
   <div class="row" style="min-height:100vh" id="body-row">
         <div id="sidebar-container" style="background-color:#edeff0;width:290px;" class="sidebar-expanded d-none d-md-block">
             <div class="card mx-auto mt-2 col-sm-10 btn btn-default" style="border-left: 5px solid blue;">
               <div class="card-body mr-auto">
                  <div class="row" style="margin-top:-10px">
                     <p>Lukman17</p>
                  </div>
                  <hr style="margin-top:-10px; width:235px;margin-left:-30px">
                  <div class="row">
                     <div class="card-text text-left">
                        <strong>V1</strong>
                        <p><small>No description</small></p> 
                     </div>
                  </div>
                  
               </div>
            
             </div>
         </div>
 
         <!-- INI ADALAH ISI KONTEN ATAU MAIN -->
         <div class="col" style="background-color:#e1e3e4">
                 &nbsp;
             <div class="container mb-5">
                 <div class="card" style="">
                     <div class="card-header col-md-12 mx-auto bg-dark text-white"style="height:70px;font-size:25px">
                           <strong>Version 1</strong>
                       </div>
                       <div class="card-title " style="background-color:#2d3339">
                           <div class="row col-9">
                              <div class="card-body mb-5">

                              </div>
                           </div>
                       </div>
                     <div class="card-body col-12">
                        <div class="row">
                           <div class="col-md-6">
                                    <h5 class="card-title" style="">VERSION DESCRIPTION</h5>
                                    <p class="card-text"><small>No Description</small></p>
                                    <div class="commennt row col-12">
                                          <label for="">Comment</label>
                                          <textarea name="" id="" cols="10" rows="3" style="width:550px"></textarea>
                                    </div>
                                    <div class="col-sm-12 text-right mt-3" style="margin-left:-17px; margint-top:5px">
                                          <a href=""class ="btn btn-primary">Comment</a>
                                       </div>
                           </div>
                           <div class="col-md-3">
                                 <h5 class="card-title" style="">VERSION 1 INCLUDES</h5>
                                 <p class="card-text"><small>No Description</small></p>
                           </div>
                           <div class="row"style="margin:auto">
                                 <div class="col-sm-7" >
                                    <a href="#"class="btn btn-light"style="border:1px solid black">Add Stems</a>
                                 </div>
                                 <div class="col-sm-7 mt-3">
                                       <a href="#"class="btn btn-light" style="border:1px solid black">Add Bounce</a>
                                 </div>
                           </div>
                        </div>
                        
                     </div>
                 </div>
                 &nbsp;
                 <!-- Akhir card -->
             
                
             </div> 
               
            
           
         </div>
     </div>
   
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>